name: Build pipeline

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v0